FROM node:17.8

RUN groupmod -g 1001 node \
  && usermod -u 1001 -g 1001 node
RUN adduser --disabled-password -uid 1000 user-poc
RUN mkdir /home/user-poc/poc/

RUN npm install -g npm@8.6.0

USER user-poc

RUN mkdir /home/user-poc/poc
WORKDIR /home/user-poc/poc 
COPY . .

EXPOSE 9091


